development:
  clients:
    default:
      database: os_dev
      hosts:
        # For some reason localhost isn't working for mongo anymore
        - 127.0.0.1:27017
      options:
  options:
    raise_not_found_error: false
    log_level: :info
docker:
  clients:
    default:
      database: os_docker
      hosts:
        - db:27017
      options:
  options:
    raise_not_found_error: false
    log_level: :info
docker-dev:
  clients:
    default:
      database: os_docker_dev
      hosts:
        - db:27017
      options:
  options:
    raise_not_found_error: false
    log_level: :info
docker-test:
  clients:
    default:
      database: os_docker_test
      hosts:
        - db:27017
      options:
  options:
    raise_not_found_error: false
    log_level: :info
production:
  clients:
    default:
      database: os_production
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
    log_level: :info
local:
  clients:
    default:
      database: <%= ENV['OS_SERVER_DATABASE_NAME'] %>
      hosts:
        # For some reason localhost isn't working for mongo anymore
        - 127.0.0.1:<%= ENV['OS_SERVER_MONGO_PORT'] %>
      options:
  options:
    raise_not_found_error: false
    log_level: :info
local-test:
  clients:
    default:
      database: <%= ENV['OS_SERVER_DATABASE_NAME'] %>
      hosts:
        - localhost:<%= ENV['OS_SERVER_MONGO_PORT'] %>
      options:
  options:
    raise_not_found_error: false
    log_level: :info
test:
  clients:
    default:
      database: os_test
      hosts:
        # For some reason localhost isn't working for mongo anymore. This is an NREL issue with IT overwriting hosts file
        - 127.0.0.1:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
